// Generated by Wrangler on Fri Aug 16 2024 15:24:15 GMT+0200 (Ora legale dell’Europa centrale)
// by running `wrangler types`

interface Env {
	RESEND_API_KEY: string;
	FROM_EMAIL: string;
	FORWARD_EMAIL: string;
}
